Week-III/MessageBoard/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

Week-III/MessageBoard/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

Week-III/MessageBoard/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

Week-III/MessageBoard/app/models/user.rb
class User < ApplicationRecord
   has_many :messages
   has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable
end

Week-III/MessageBoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end
end

Week-III/MessageBoard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end
  def destroy
    @comment.destroy
    redirect_to message_path(@message)

  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
    def find_message
      @message = Message.find(params[:message_id])
    end
    def find_comment
      @comment = @message.comments.find(params[:id])

    end
end

Week-III/MessageBoard/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @messages = Message.all.order("created_at DESC")

  end
  def new
    @message = current_user.messages.build
  end
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  def show
  end
  def edit

  end
  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end
  def destroy
    @message.destroy
    redirect_to root_path
  end
  private
  def message_params
    params.require(:message).permit(:title, :description)
  end
  def find_message
    @message = Message.find(params[:id])
  end
end
    

Week-III/MessageBoard/app/helpers/messages_helper.rb
module MessagesHelper
end

Week-III/MessageBoard/app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
  <div class="links">
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to 'Edit', edit_message_comment_path(comment.message,comment) %>
        <%= link_to 'Delete', message_comment_path(comment.message,comment), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    <% end %>
  </div>
</div>

Week-III/MessageBoard/app/views/comments/_form.html.erb
<%= simple_form_for([@message,@message.comments.build]) do |f| %>
  <%= f.input :content, label: 'Comment' %>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end%>

Week-III/MessageBoard/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
	<%= simple_form_for([@message, @comment]) do |f| %>
	  <%= f.input :content, label: 'Comment' %>
	  <%= f.button :submit %>
	<% end %>
	</div>
</div>

Week-III/MessageBoard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Message Board", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li> <%=link_to 'Sign Up', new_user_registration_path %> </li>
          <% if user_signed_in? %>
            <li><%= link_to "Edit #{current_user.name}",edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
          <% if user_signed_in? %>
            <p><%= link_to 'New Message', new_message_path, class: "navbar-right navbar-text navbar-link" %></p>
          <% end %>
      </div>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>